name: markdown-lnk-check-comment

on:
  workflow_run:
    workflows: [ "markdown-link-check" ]
    types:
      - completed

defaults:
  run:
    shell: pwsh
#env:
#  WORKFLOW_HEAD_SHA: ${{ github.event.workflow_run.head_sha }}

jobs:
  main:
    name: Markdown Link Check log parser
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
#      with:
#        ref: ${{ env.WORKFLOW_HEAD_SHA }}
    - name: Run markdown link check log parser
      id: mlc-log-parser
      uses: edumserrano/markdown-link-check-log-parser@v1
      with:
        run-id: '${{ github.event.workflow_run.id }}'
        job-name: 'Run Markdown Link Check'
        step-name: 'Markdown Link Check'
        only-errors: 'false'
        output: 'step, json, md'
        json-filepath: './mlc-json-result.json'
        markdown-filepath: './mlc-md-result.md'
    - name: Create comment
      uses: peter-evans/create-or-update-comment@v3
      with:
        issue-number: 1
        body: |
          $result = '${{ steps.mlc-log-parser.outputs.mlc-result }}' | ConvertFrom-Json
          Write-Output "Total files checked: $($result.TotalFilesChecked)"
          Write-Output "Total links checked: $($result.TotalLinksChecked)"
          Write-Output "Has erros: $($result.HasErrors)"
          $resultAsJsonIndented = ConvertTo-Json -Depth 4 $result
          Write-Output $resultAsJsonIndented # outputs the markdown link check result as an indented JSON string
        reactions: '+1'